### ISSUE TITLE
Quick Notes New Features

### ISSUE THREAD

**Issue by Cotrox** [gabrielchristino/zepp_quick_notes#1]
Hi Mate, I really love your project and i'm using it on my Amazfit GTS 4 mini but how you can see there are a lot of txt view app for ZeppOS. I think yours is very nice but I want to suggest you to add some new things:

- The ability to write a text file directly from the **Zepp App > App Settings** because sometimes can be better to write from phone (for longer texts).
- The ability to choose from the actual **T9** keyboard to a **different keyboard layout** (extended for exemple). I think that T9 is the best solution for a little screen but you know.. people love the opportunity to choose XD
- Change the App Icon making one more fused with ZeppOS Design. If you need help I can provide you a new Icon.. i'm a Designer and you can find some projects there https://www.behance.net/Cotrox or there https://www.instagram.com/ctr_design7/

Great Jov anyway! 😀

**Comment by gabrielchristino** [comment]
Hello, I'm glad you're using my project and thanks for your suggestions!

- The ability to write direct from the Zepp App is the next item on my To-do list.
- For the extended keyboard, I'm looking for a way to an "ergonomic" fit on a small screen. Sometimes it's easier to use than a T9 (not everybody has the habit to use this type).
- I was looking your design, and it's great, I love it! I'll contact you when I go to change the icon for be better!

Thank you so much! :grinning: 
This channel will always be open for ideas and suggestions!

**Comment by Cotrox** [comment]
Thank you ❤️ I will wait for the update! Have you a release date for it?

Giuseppe A. Cotroneo
________________________________
Da: Gabriel Christino Cordeiro dos Santos ***@***.***>
Inviato: Thursday, March 9, 2023 5:35:42 PM
A: gabrielchristino/zepp_quick_notes ***@***.***>
Cc: Giuseppe Antonino Cotroneo ***@***.***>; Author ***@***.***>
Oggetto: Re: [gabrielchristino/zepp_quick_notes] Quick Notes New Features (Issue #1)


Hello, I'm glad you're using my project and thanks for your suggestions!

  *   The ability to write direct from the Zepp App is the next item on my To-do list.
  *   For the extended keyboard, I'm looking for a way to an "ergonomic" fit on a small screen. Sometimes it's easier to use than a T9 (not everybody has the habit to use this type).
  *   I was looking your design, and it's great, I love it! I'll contact you when I go to change the icon for be better!

Thank you so much! 😀
This channel will always be open for ideas and suggestions!

**Comment by gabrielchristino** [comment]
Until the end of month I'll release an update :grin: 

Gabriel Christino

**Comment by gabrielchristino** [comment]
Hello! It’s updated now on Zepp app, the new version 1.0.3.

Thanks a lot!!

**Comment by Cotrox** [comment]
Really nice Job!

I just want you to suggest some things to improve it!

• For T9 and Extended Keyboard type if you write a text with more then 3 lines you can’t see the rest of the text you are writing because the area is not scrollable. I think you can find a way to let user see all the part of the text he is writing. For exemple adding a button on the top part of the keyboard (with buttons confirm, space and delete). The new button have to be something that let user close the keyboard and see the readble text and let him to scroll the text if it is longer then the screen. Then, you have to put in this screen a button to return to the edit mode.
Another things that you can improve is that, if user can read 3 lines but text is going to be longer then 3 lines you have to scroll the text auromatically to let user see the last part of thext and not the start of it. this is very important to see what we are writing during live edits mode session.

• For extended keyboard only, as I told you before, you can see 3 lines of text and keyboard have an hight that let you see these 3 lines. But if you make a different layout with a higher height (letting just to read 1 line) you can reorganize chars buttons to increese their width. It is possible bcause if keyboard has more height availble you can organize buttons in more lines.

• For splitted keyboard i think it is the best way you found and it os amazing BUT you have to make as fixed the top part of the keyboard and the writed text. I mean that when you let user go to the right keyboard he have to see writed text and top options too.

Thanks for your time and I hope you can understand my bad english! Ahahah

Giuseppe A. Cotroneo
________________________________
Da: Gabriel Christino Cordeiro dos Santos ***@***.***>
Inviato: Monday, March 20, 2023 2:00:48 PM
A: gabrielchristino/zepp_quick_notes ***@***.***>
Cc: Giuseppe Antonino Cotroneo ***@***.***>; Author ***@***.***>
Oggetto: Re: [gabrielchristino/zepp_quick_notes] Quick Notes New Features (Issue #1)


Closed #1<https://github.com/gabrielchristino/zepp_quick_notes/issues/1> as completed.
